#!/bin/bash

# List of source files with "lib_" prefix
source_files=("lib_0-isupper.o" "lib_1-memcpy.o" "lib_2-strlen.o" "lib_3-strcmp.o" "lib_5-strstr.o"
              "lib_0-memset.o" "lib_1-strncat.o" "lib_2-strncpy.o" "lib_3-strspn.o" "lib_6-abs.o"
	                    "lib_0-strcat.o" "lib_100-atoi.o" "lib_3-islower.o" "lib_4-isalpha.o" "lib_9-strcpy.o"
			                  "lib_1-isdigit.o" "lib_2-strchr.o" "lib_3-puts.o" "lib_4-strpbrk.o")

# Loop through the source files and rename them
for source_file in "${source_files[@]}"; do
    # Extract the base filename without the "lib_" prefix
        new_name="${source_file#lib_}"

    # Rename the file
        mv "$source_file" "$new_name"

    # Print a message indicating the renaming
        echo "Renamed $source_file to $new_name"
	done
	